### ISSUE TITLE
OpenWhisk Slack package example is missing hash in channel name

### ISSUE THREAD

**Issue by osowski** [IBM-Bluemix/docs#101]
The Slack example for OpenWhisk requires the leading hash in the channel name for it to work properly, however the included example is missing it.

https://github.com/IBM-Bluemix/docs/blob/master/openwhisk/openwhisk_catalog.md

Incorrect:  `wsk package bind /whisk.system/slack mySlack --param url 'https://hooks.slack.com/services/...' --param username 'Bob' --param channel 'MySlackChannel'`

Correct:  `wsk package bind /whisk.system/slack mySlack --param url 'https://hooks.slack.com/services/...' --param username 'Bob' --param channel '#MySlackChannel'`

**Comment by sefuhrer** [comment]
Thank you for your attention to detail! I am updating the documentation with this fix and hope to have these updates live on Friday.
