### ISSUE TITLE
boilerplate starter doc needs maintenance details

### ISSUE THREAD

**Issue by slaupster** [IBM-Bluemix/docs#1034]
We really need to put instructions on how to maintain the BP app once its created.  In support we are constantly telling people how to do this and its not documented anywhere.

I think the best place for this is actually in docs/starters/IoT/iot500.md.

This page is pretty busy, which makes it unlikely anyone will actually read any of it.  I think it should be much shorter if possible, but needs to include the information relevant to maintaining the BP, even if the detail is actually in another page, but linked from iot500.

The detail is essentially:

Once this boilerplate application is created, it is not automatically updated.  If updates or changes to the application are needed, the best way to do this is to add a GIT repository which will allow you to edit the app and redeploy the application.

To add GIT, navigate to application using the Bluemix console.  Select Overview tab and under "Continuous delivery" click the link to add a GIT repository.  Use jazzhub to mak changes to the application and redeploy the changes to your instance.

**Comment by HNorlen** [comment]
@slaupster Cloning this issue in the internal Docs repo here: https://github.ibm.com/Watson-IoT/Docs/issues/531

Closing the issue here.
