### ISSUE TITLE
Start Step 6 uses https://app_name.AppDomainName but app_name could be different from host name

### ISSUE THREAD

**Issue by chengxing1987** [IBM-Bluemix/docs#1055]
In docs/starters/install_cli.md, the six step is **Access your app by browsing to https://app_name.AppDomainName**, but it is possible that app_name is not equal to host name.

**Comment by zzDRT** [comment]
HI Jenifer,  I have not had a chance to look at this.  More or less the same problem is also in issue 772.
If you have time please take a look .  Thanks,  DanaT

**Comment by zzDRT** [comment]
Jeff,  how do you code the host name in markdown.  I tried using app_url in step 6 but that does not work.

**Comment by zzDRT** [comment]
This is resolved by issue https://github.ibm.com/Bluemix/core-ui-cdl/issues/1668.
It is currently working in dev-console
