### ISSUE TITLE
Path not updated if /etc/zshenv is missing

### ISSUE THREAD

**Issue by j4zzcat** [IBM-Bluemix/docs#114]
My OS X with zsh (installed from brew), doesn't have a /etc/zshenv, only /etc/zshrc.

**Comment by jeffchi** [comment]
@j4zzcat 

Hi, could you please let us know which page you're referring to?  Did a brutal search in all the content files but no hit for `etc/zshenv` though.

**Comment by j4zzcat** [comment]
I'm referring to the installation package of the bluemix command line tools (http://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/Bluemix_CLI_0.3.1.pkg). The installation tries to update /etc/zshenv, which is missing on machine.

**Comment by boyang9527** [comment]
thanks for reporting this, will address this issue.

**Comment by archerzz** [comment]
This should have been fixed. Please verify the latest build. Thanks.

**Comment by archerzz** [comment]
This should have been fixed in the coming release. Thanks for reporting.
