### ISSUE TITLE
Uploading Data

### ISSUE THREAD

**Issue by alewitt** [IBM-Bluemix/docs#12]
I have to upload semi-large data files (20-30GB). In object storage v1, i was able to find a way to do a curl that would upload a compressed file, then decompress it once it finished uploading.

What can i do in object storage v3 that would allow me to do the same thing? I dont want to have to upload a 20+ GB file.

**Comment by jiamaoIBM** [comment]
Does the "Adding files larger than 5 GB to a container" section in the Object Storage guide answer your question.

https://new-console.ng.bluemix.net/docs/services/ObjectStorage/index.html#using-swift-cli

**Comment by jeffchi** [comment]
@alewitt  we're closing this issue.  Please let us know if any concern with the update.
:+1:
