### ISSUE TITLE
New Frankfurt region missing in the region selection

### ISSUE THREAD

**Issue by SHuesing** [IBM-Bluemix/docs#1251]
At the very bottom of the documentation page, you can choose a region. The new European region in Frankfurt is missing.
![image](https://cloud.githubusercontent.com/assets/25974096/24505726/3f544bc2-155b-11e7-9287-923b67858b2f.png)

**Comment by jenschlot** [comment]
Duplicate of https://github.ibm.com/Bluemix/docs/issues/1256
