### ISSUE TITLE
Where do find OpenWhisk accessKey and accessToken?

### ISSUE THREAD

**Issue by csantanapr** [IBM-Bluemix/docs#127]
On the docs https://new-console.ng.bluemix.net/docs/openwhisk/openwhisk_mobile_sdk.html

It mentions to setup credentials like:

let credentialsConfiguration = WhiskCredentials(accessKey: "myKey", accessToken: "myToken")
let whisk = Whisk(credentials: credentialsConfiguration!)

Where in the Console Dashboard for OpenWhisk can I find the values for Key and Token?

**Comment by paulcastro** [comment]
@csantanapr I'm updating the mobile docs to include more clear instructions.  That said, from the CLI you can do:

wsk property get --auth
which will list your key and token as "key:token"

From the dashboard, navigate to the OpenWhisk homepage and click on "Configure CLI".  It will show you the values in step 2 where you set the auth value "wsk property set --auth key:token"

**Comment by sefuhrer** [comment]
@csantanapr Paul's updates to the iOS docs have been published. Hopefully they address your issue.
