### ISSUE TITLE
Timezone for openwhisk alarm package

### ISSUE THREAD

**Issue by parente** [IBM-Bluemix/docs#130]
I don't see anywhere in the OpenWhisk doc about the Alarm package what timezone will be used to interpret cron strings involving hours and longer time scales. For instance:

`0 1 * * * *` means fire the trigger at 1 AM every day. But 1 AM in what timezone? Is it UTC?

**Comment by rabbah** [comment]
It should be UTC, yes.

**Comment by parente** [comment]
Cool. That should probably go in the doc somewhere.
