### ISSUE TITLE
OpenWhisk links to rest API docs broken

### ISSUE THREAD

**Issue by csantanapr** [IBM-Bluemix/docs#1322]
Reported by user on Slack

[Hope this is the right channel to ask :cool_dude:]
There seem to be an issue with a link on the openwhisk page: On https://console.ng.bluemix.net/docs/openwhisk/openwhisk_reference.html#openwhisk_ref_restapi
when you click on *REST API References* you are transferred to `https://new-console.{domainname}/apidocs/98`. The domainname binding seems to be missing…
The correct link probably should be `https://console.ng.bluemix.net/apidocs/98`

**Comment by sefuhrer** [comment]
I fixed this in the toc. the domain value does not work in toc.xml generated by toc file.

**Comment by csantanapr** [comment]
Thanks @sefuhrer closing issue merged here https://github.com/IBM-Bluemix/docs/commit/fa3feaa23a0bcdc8fa00204e5ae5d34973573b65#diff-574a75c0b818d77629872c2c33761b5f
