### ISSUE TITLE
Improve clientId info for applications

### ISSUE THREAD

**Issue by benbakowski** [IBM-Bluemix/docs#1331]
We need to make it clearer that MQTT clientIds should be unique, and provide more context on what this means.

In MQTT Connectivity for Applications, we appear just to say:

The MQTT client ID is in the format: a:orgId:appId

We should provide examples, and emphasise that each client should use a unique clientId (unless you're using A:orgId:appId clientIds.

**Comment by HNorlen** [comment]
@benbakowski 
Moved to internal docs repo: https://github.ibm.com/Watson-IoT/Docs/issues/674

Closing here!
