### ISSUE TITLE
Document ulimits for OpenWhisk Docker actions

### ISSUE THREAD

**Issue by parente** [IBM-Bluemix/docs#134]
When developing a Docker action for OpenWhisk, I hit a `OSError: [Errno 24] Too many open files` error. It would be good to document what the ulimits are on Docker containers to help scope development.

**Comment by csantanapr** [comment]
@parente Thank you for reporting the problem. 
The current limit is 64 files 512 process 
Will keep this issue open, until pubic facing docs are out.

If you want more details you can find here openwhisk/openwhisk#342

**Comment by csantanapr** [comment]
This is fix now, you can find info in system limits section https://new-console.ng.bluemix.net/docs/openwhisk/openwhisk_reference.html#openwhisk_syslimits
