### ISSUE TITLE
Incorrect path in Application Publishing events section

### ISSUE THREAD

**Issue by miketran78727** [IBM-Bluemix/docs#1367]
The path on this page  https://console.ng.bluemix.net/docs/services/IoT/applications/api.html#api is incorrect.

The path should be /api/v0002/**application**/types/typeId/devices/deviceId/events/eventId

See swagger file : https://docs.internetofthings.ibmcloud.com/apis/swagger/v0002/http-messaging.html

**Comment by CaroMac** [comment]
Thanks Mike. Will update.

**Comment by CaroMac** [comment]
verified in prod
