### ISSUE TITLE
Link to SDK for Node.js Broken.

### ISSUE THREAD

**Issue by hobertbush** [IBM-Bluemix/docs#175]
On the following link:
https://console.ng.bluemix.net/docs/services/ObjectStorage/index.html

Under COMPATIBLE RUNTIMES, the link for SDK for Node.js is broken and should probably go the following location:

https://console.ng.bluemix.net/docs/runtimes/nodejs/index.html#nodejs_runtime

**Comment by sefuhrer** [comment]
@zzdrt or @randala can you guys take a look?

**Comment by zzDRT** [comment]
This has been fixed.
