### ISSUE TITLE
Securing Apps: Public Region IPs

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/docs#184]
The content in the [Securing Apps](https://github.com/IBM-Bluemix/docs/blob/master/manageapps/secapps.md) page is outdated in some respects. It still lists the region IP addresses for the DNS routing when we now have hostnames for the routers, so a CNAME is more appropriate. I would make sure all info on [Tony's blog post](https://developer.ibm.com/bluemix/2014/09/28/ssl-certificates-bluemix-custom-domains/) (at the minimum) is included in this doc.

**Comment by Crystal4545** [comment]
@JakePeyser  Thanks for spotting this.  The doc is updated to reflect the CNAME.  Before we roll out the updates, please take a pass for the changes:  https://github.com/IBM-Bluemix/docs/pull/213 
Thanks.

**Comment by plindblue** [comment]
Closing issue since the changes have already been made.
