### ISSUE TITLE
strongSwan config is missing Bluemix VPN Gateway IP

### ISSUE THREAD

**Issue by rmey** [IBM-Bluemix/docs#185]
https://github.com/IBM-Bluemix/docs/blob/master/services/vpn/vpn_onpremises.md
The VPN config for strongSwan is not clear about how to use the Bluemix Gateway IP address in the configuration /etc/ipsec.all.conf. The Cisco and Viata config examples reference this IP but not the strongSwan example. Make a search for the example IP
    IBM VPN gateway IP address: **134.168.8.164 **
How should the onPrem system reach the BMX VPN without specifying the Gateway IP?

**Comment by nemivant** [comment]
The example is updated and now shows the IBM VPN gateway IP address. 
https://console.ng.bluemix.net/docs/services/vpn/vpn_onpremises.html#strongswan
