### ISSUE TITLE
dashDB steps missing build pack

### ISSUE THREAD

**Issue by hobertbush** [IBM-Bluemix/docs#191]
On step 5 of the following link we should add the buildpack
https://console.ng.bluemix.net/docs/services/dashDB/index-gentopic1.html#managing_instance

For example, it should be the following:
cf push <app-name> -b https://github.com/zendtech/zend-server-php-buildpack-bluemix
or the db2phpbuildpack

cf push <app-name> -b https://github.com/ibmdb/db2heroku-buildpack-php

Source:
https://hub.jazz.net/project/ibmdatabase/dashDB/overview#https://hub.jazz.net/git/ibmdatabase%252FdashDB/list/master/samples/dashDBPHP

**Comment by rimask** [comment]
Hi Hobert,
Thank you for your feedback comment. I completed the changes to step 5 that you approved today. The changes will be viewable sometime today after a rebuild is done.

Cheers.
Rimas
