### ISSUE TITLE
Your support is ugly! and did your support system dead? and your billing system dead too.

### ISSUE THREAD

**Issue by netroby** [IBM-Bluemix/docs#282]
I have try for bluemix for several days.
Very impressive of the platform.
I like your docker container hosting.
And i want to upgrade account to paid.

But your billing system broken. i submit my credit card information. but the system not success let me upgrade.

I post help ticket in your support system. but day by day goes. not support reply. 

Nobody care?
What the bad cloud platform !!!
IBM bluemix, just like a joke.

**Comment by bwentwor** [comment]
@netroby Did you submit the ticket using one of the @bluemix.net email addresses, such as billing@bluemix.net or support@bluemix.net? On February 8, 2016, the following blog article was published to announce the removal of those email addresses and describe the most efficient ways to get your concern resolved: https://developer.ibm.com/bluemix/2016/02/08/get-bluemix-support/
The previously referenced blog article provides information about submitting a ticket and an alternative if you cannot use the support widget. 

In addition, you might find an answer to your credit card issue in our Common Bluemix ID and Billing Questions (FAQ) blog at this URL: https://developer.ibm.com/bluemix/2016/04/26/bluemix-id-and-billing-faq/

If the FAQ does not address your billing concern, please use the support widget on the Bluemix dashboard to submit your ticket and our Support team will be happy to help. 

We apologize for any delay in getting your concern addressed.

**Comment by netroby** [comment]
Your bluemix.net still having these email address.

https://support.eu-gb.bluemix.net/gethelp/


and today i recieved your response. my ticket was responsed by one of your staff. I success upgrade my account to paid as you go.

Thanks for you reply
