### ISSUE TITLE
IoT: Node.js: Be more specific about function arguments

### ISSUE THREAD

**Issue by asmod3us** [IBM-Bluemix/docs#285]
In the [Node.js doc for applications](https://github.com/IBM-Bluemix/docs/blob/master/services/IoT/applications/libraries/nodejs.md), and in a lot of other places, can we be more specific about the nature of the function arguments? I.e., what are

- deviceType
- deviceId
- eventType
- format
- payload - Device event payload
- topic - Original topic

As a developer, I'd be interested to learn from the documentation about 
- restrictions on type of the argument (string, number, json, object, ...)
- expected format (regex, structure, ...)
- what's the maximum/minimum length/value, if any
etc.

**Comment by HNorlen** [comment]
Thanks for your suggestion. We will look into enhancing the function argument descriptions.

**Comment by michellepurcell** [comment]
@CaroMac 
Hello Caroline,
I think you completed the required updates as per your update in the ID docs equivalent issue: https://github.ibm.com/Watson-IoT/Docs/issues/177
Can you confirm whether this issue can now be closed?
Thanks
Michelle

**Comment by michellepurcell** [comment]
Received confirmation from Caroline that this issue is now fixed and can be closed.
