### ISSUE TITLE
Link to simulateddevice is broken

### ISSUE THREAD

**Issue by ekstrom-ibm** [IBM-Bluemix/docs#286]
On the page for [Creating and connecting a Node-RED device simulator](https://console.ng.bluemix.net/docs/services/IoT/nodereddevice_sample.html#devices) step 1.e., there is a reference to http://simulatedDevice.mybluemix.net from where you could download a Node-RED flow - however the link is broken.

**Comment by HNorlen** [comment]
@ekstrom-ibm The `http://simulatedDevice.mybluemix.net` link is an example of what the Node-RED link might look like, and is not an active link. The link will differ depending on the name that you gave Node-RED when you instantiated it. The documentation is a little unclear, and will be improved.

> e. Click the app link at the top of the page to open Node-RED.
> Example: http://simulatedDevice.mybluemix.net

**Comment by ekstrom-ibm** [comment]
Thanks - that was a clarification for a newbie.

**Comment by HNorlen** [comment]
Text was updated a while back:
> Click the Routes link to open Node-RED.
> Example: http://simulatedDevice.mybluemix.net
