### ISSUE TITLE
Link to DEVELOP is broken

### ISSUE THREAD

**Issue by ekstrom-ibm** [IBM-Bluemix/docs#287]
Logging into Bluemix - go to your dashbard - on the top right click on Develop 
![capture](https://cloud.githubusercontent.com/assets/19836090/15931191/f6ee4d88-2e56-11e6-9cbe-8dfb452b2df9.PNG)
and it gives you a "404: Resource not found":

**Comment by sefuhrer** [comment]
@ekstrom-ibm I only see this when signing into staging - I do not see it on production. Can you confirm this is an issue on production?

**Comment by ekstrom-ibm** [comment]
I don't know how to selectively sign into staging or production! Could you elaborate on that?

However, the DEVELOP topic have vanished from my menu:
![capture2](https://cloud.githubusercontent.com/assets/19836090/15955441/8d2ceb8a-2ee1-11e6-8e7b-90b0d8cbd90d.PNG)

**Comment by sefuhrer** [comment]
@ekstrom-ibm you would need to be behind the blue firewall and add stage1 to the url path - console.stage1.ng....

**Comment by ekstrom-ibm** [comment]
OK - in that case I'm sure I wasn't there as we saw the same on a client account and machine.
Anyways - it appears to no longer being an issue.
