### ISSUE TITLE
Twitter Insights REST API Link Dead

### ISSUE THREAD

**Issue by jthomas** [IBM-Bluemix/docs#360]
https://new-console.ng.bluemix.net/docs/services/Twitter/twitter_rest_apis.html#rest_apis

Links to.... 

https://cdeservice.ng.mybluemix.net/rest-api/

Which is 404'ing.

**Comment by patsmith-ibm** [comment]
This is a known issue that has been resolved and will go into production on July 7th 
https://github.ibm.com/Bluemix/Bluemix-doc-framework/issues/68
