### ISSUE TITLE
Delivery Pipeline/DevOps Services topic needs to be updated

### ISSUE THREAD

**Issue by lamibm** [IBM-Bluemix/docs#388]
This topic - https://hub.jazz.net/docs/deploy_ext/#globalize needs to be reviewed and updated because the implementation of IBM GLobalization PIpeline into DevOps Services has been changed due to the GA of the IBM Globalization Pipeline service. 

1. The development contact to review the steps is Jacob Garcowski 
2. There is a new video which should be linked to. The current video is out of date.

See the new video at:  https://www.dropbox.com/s/u95i1b0ur7d0j9y/DevOps%20Pipeline.mp4?dl=0

**Comment by maxbridges** [comment]
@lamibm The DevOps Services documentation has migrated to the Bluemix Docs collection. This is not yet reflected in the IDS UI. The [most recent version of this page](https://new-console.ng.bluemix.net/docs/services/DeliveryPipeline/deliverypipeline_extension.html) does not include that subsection. I can remove it from the DevOps Services docs.

Going forward, the Globalization Pipeline docs can be found at https://new-console.ng.bluemix.net/docs/services/GlobalizationPipeline/index.html.

**Comment by lamibm** [comment]
Hi Max -- Okay.. I am actually the Offering Manager for Globalization Pipeline. We are integrated into DevOps services as a stage. Of course we will  include a mention of the DevOps Services integration in our docs, but I wonder if there should be a pointer in the DevOps services doc. This is an important integration feature and is demo'd as part of the Bluemix garage method.

**Comment by maxbridges** [comment]
@lamibm Do you have an information developer who can own a chunk of https://new-console.ng.bluemix.net/docs/services/DeliveryPipeline/deliverypipeline_extension.html ? That would make sense to me.
