### ISSUE TITLE
Mandatory and optional metadata for custom service brokers

### ISSUE THREAD

**Issue by data-henrik** [IBM-Bluemix/docs#435]
admin/index.md shows a sample JSON document with metadata a custom service broker could return. It does not have information which fields are possible, which are mandatory or optional and about their purpose. This should be added

**Comment by mekaufman** [comment]
#655 on internal work docs issue board has been created to contain this work by end of August

**Comment by mekaufman** [comment]
@data-henrik The build with the updates has been requested. You should be able to see the updated information later today here: https://new-console.ng.bluemix.net/docs/admin/index.html#servicebrokerui
