### ISSUE TITLE
Wrong section identified in Step 1 for configuring DB

### ISSUE THREAD

**Issue by ValerieLampkin** [IBM-Bluemix/docs#621]
The "settings" section does not have info about Cloudant DB.  User will need to choose the "extensions" in navigation bar to see the available DB to configure

**Comment by ValerieLampkin** [comment]
![extensions](https://cloud.githubusercontent.com/assets/8366144/18598541/39596636-7c21-11e6-89cd-6b758177044d.png)

**Comment by HNorlen** [comment]
Resolved, will go out with next production build. Closing
