### ISSUE TITLE
Broken link to CLI installers

### ISSUE THREAD

**Issue by johnwalicki** [IBM-Bluemix/docs#624]
The Bluemix CLI page at
   https://github.com/IBM-Bluemix/docs/blob/master/starters/install_cli.md
has a broken link that points to 
   clis.stage1.ng.bluemix.net/ui/home.html
It should point to 
   http://clis.ng.bluemix.net/ui/home.html

**Comment by ChristyWatkins** [comment]
Found this in my verification for [https://github.ibm.com/Bluemix/docs/issues/568](https://github.ibm.com/Bluemix/docs/issues/568) as well. Fixed the issue earlier this morning. Queued for building. Will update when the build is public
