### ISSUE TITLE
Bad link to WIoTP  APIs Doc

### ISSUE THREAD

**Issue by leandrodvd** [IBM-Bluemix/docs#688]
While searching for the Watson IoT Platform API documentation Google pointed me to this page
http://www.ibm.com/internet-of-things/roles/iot-developer/

There are several specific links there to the IoT Platform APIs

But instead of sending me to the specific API page listed, all links (or most or some of them), send me to this page:
https://console.ng.bluemix.net/docs/services/IoT/index.html

That is not at all a specific API documentation page, but a generic doc page about the IoT Platform service.

When I google for Watson IoT API it should point me straight forward to what I want, the direct API doc page, not a generic page.

**Comment by HNorlen** [comment]
Thanks much for your input.

The API docs are now linked directly from the site navigation under: References > APIs

They are also linked to from the Resources tab of the Getting started with Watson IoT Platform topic.

Information about the API and links to the API docs are also available at: Developing for devices > HTTP Rest API for Devices.

The API docs are currently being worked on, and Google searches should be more spot on in the future.

Hope that helps!
