### ISSUE TITLE
It is hard to find the link to the API Reference of Watson IoT Platform in the service documentation

### ISSUE THREAD

**Issue by leandrodvd** [IBM-Bluemix/docs#689]
I spent some fair high time looking for the Watson IoT Platform API Reference

(this one: https://docs.internetofthings.ibmcloud.com/swagger/v0002.html?cm_mc_uid=32778390876414762122710&cm_mc_sid_50200000|BLUEMIX=1476383596#/)

I was able to finally find it at the WIoTP service doc home page
(this one: https://console.ng.bluemix.net/docs/services/IoT/index.html)

But it is in the end of the page, in the middle of some text, really hard to find.

As a developer I would love to find the link to "API REFERENCE"  shinning and easily accessible at the top of the page or at least in the side menu (note that there is a REFERENCE item in the side menu but nothing related to the API Reference I was looking for)

**Comment by HNorlen** [comment]
Thanks much for your input. 

The API docs are now linked directly from the site navigation under: References > APIs

They are also linked to from the Resources tab of the Getting started with Watson IoT Platform topic. 

Information about the API and links to the API docs are also available at: Developing for devices > HTTP Rest API for Devices.

Hope that helps!
