### ISSUE TITLE
Log Retention should be 7 days for Public and 30 days for Dedicated.

### ISSUE THREAD

**Issue by lionelmace** [IBM-Bluemix/docs#694]
In the section "Monitoring and logging with Cloud Foundry", the **Log Retention** states

_In Bluemix Cloud Foundry apps, log data is stored for 30 days by default._

It should be **replaced by**

_In Bluemix Cloud Foundry apps, log data is stored by default for **30 days in Bluemix Dedicated/Local and for 7 days in Bluemix Public**._

Lionel

**Comment by bhpratt** [comment]
Currently CF Apps Dedicated / Local are separated out into topics that do specify the 30 day log retention - https://new-console.ng.bluemix.net/docs/monitoringandlogging/cfapps_ml_logs_dedicated_ov.html#container_ml_logs_dedicated_ov

I will update this topic to clarify log retention for Public - https://new-console.ng.bluemix.net/docs/monitor_log/monitoringandlogging.html#log_retention

Longer term I'm looking at how this section can be more integrated (and how we might integrate w/the container logging and monitoring topics as well).

**Comment by bhpratt** [comment]
Verified the logging caps is correctly updated in prod. Closing issue.
