### ISSUE TITLE
Incorrect service name reference for Watson IoT Platform on the Bluemix docs home page

### ISSUE THREAD

**Issue by michellepurcell** [IBM-Bluemix/docs#698]
Problem: Incorrect product name usage for the IBM Watson IoT Platform service on the Bluemix docs home page.

https://console.ng.bluemix.net/docs/

![incorrect wiotp product name](https://cloud.githubusercontent.com/assets/19187948/19479942/e95e1454-9540-11e6-9598-aea50ae67d6d.png)

"Internet of Things Platform" should be  "Watson IoT Platform" as this is the official short name.
"IBM Watson IoT Platform" is the full name.

**Comment by sefuhrer** [comment]
Hey Michelle, 

This comes from the catalog dynamically, so you would need to work with the catalog UI string to fix this value.

**Comment by sefuhrer** [comment]
@michellepurcell https://new-console.ng.bluemix.net/catalog/services/internet-of-things-platform/
Can you work with your dev team to correct the catalog?

**Comment by durera** [comment]
The name "internet of things platform" was selected by offering management after lengthy discussion, even though it's not our actual name.  Have you cleared this change with them.  All of the above was pointed at the time, but the decision was taken to very specifically call our service "internet of things platform" in the catalog.  IIRC it went right up to Neil who decided the final name.

**Comment by HNorlen** [comment]
@durera Understood! The issue here is that Bluemix docs are pulling this name in directly to the navigation. Thus there is no entry for "Watson Iot Platform." Let us ponder this, and see if some other fix can be applied.

**Comment by michellepurcell** [comment]
@sefuhrer & @durera 
Thanks for reviewing. Moving this issue (and thread) over into the internal docs-staging repo for further investigation and discussion. Closing this one.
