### ISSUE TITLE
Broken link in documentation to "Scalable Applications"

### ISSUE THREAD

**Issue by rmoussal** [IBM-Bluemix/docs#752]
In the WIoTP java documentation : https://console.ng.bluemix.net/docs/services/IoT/applications/libraries/java.html

clicking on the "Scalable Applications" link (part of shared-subscription in the constructor) results in page not found; here's the link for reference: https://console.ng.bluemix.net/docs/services/IoT/applications/libraries/mqtt.html#/scalable-applications#scalable-applications

**Comment by HNorlen** [comment]
Thanks for the notification. The link should be: https://console.ng.bluemix.net/docs/services/IoT/applications/mqtt.html#scalable_apps
Will update the docs.

**Comment by michellepurcell** [comment]
This issue is now fixed. Many thanks for taking the time to provide feedback.
