### ISSUE TITLE
[openwhisk] Update "Setting up OpenWhisk CLI" menu item

### ISSUE THREAD

**Issue by csantanapr** [IBM-Bluemix/docs#770]
On the page https://console.ng.bluemix.net/docs/openwhisk/index.html#openwhisk_start_configure_cli

Change menu item from "Setting up OpenWhisk" to "Setting up OpenWhisk CLI"
![image](https://cloud.githubusercontent.com/assets/1094878/19861869/8b458662-9f64-11e6-8e54-b52f81b1280c.png)

**Comment by sefuhrer** [comment]
https://console.ng.bluemix.net/docs/openwhisk/index.html
fixed
