### ISSUE TITLE
broken link for MQTT standards 

### ISSUE THREAD

**Issue by ValerieLampkin** [IBM-Bluemix/docs#783]
In this part of doc:  "For information about the versions of MQTT that are supported by Watson IoT Platform, see Standards and requirements"  the link is not working

**Comment by michellepurcell** [comment]
@ValerieLampkin - Thank you for reporting this. Working on a fix for this today.

**Comment by HNorlen** [comment]
@michellepurcell The linked to topic is currently in final review. Unclear why there is already a link to it.

**Comment by michellepurcell** [comment]
@HNorlen - Slip > Cracks > Parallel universe?
Added a note to prevent the docs-staging version that has the link to the unpublished topic from going out prematurely again. Our 'push to production' process should in theory prevent similar issues.

**Comment by HNorlen** [comment]
Unless the pusher is also the author of the incorrect content to be pushed, and completely forgot about it, and pushed nevertheless.
