### ISSUE TITLE
Bluemix cf manifest supports hosts and domains parameters

### ISSUE THREAD

**Issue by vbontempi** [IBM-Bluemix/docs#79]
I tested successfully that Bluemix cf manifest version is supporting hosts and domains parameter like described in cf documentation
https://docs.run.pivotal.io/devguide/deploy-apps/manifest.html#hosts

**Comment by jeffchi** [comment]
https://new-console.ng.bluemix.net/docs/manageapps/depapps.html#appmanifest

The host and domain parameters are listed on the page above.
