### ISSUE TITLE
The http API should include as examples the standard ports

### ISSUE THREAD

**Issue by MaeveOReilly** [IBM-Bluemix/docs#826]
https can be on 443.  This should be also noted.  Use of 1883/8883 can be difficult as they are not standard and therefore not by default open in firewalls.  

Note having 443 actually in a URL can actually break fussy stuff.  It should be given as example:  

https://orgId.messaging.internetofthings.ibmcloud.com/api...

(I have edited this as port 80 is not possible, must be then 1883 for http).

**Comment by michellepurcell** [comment]
Closing issue as this update was completed in early December for the 79 push to prod.

https://console.ng.bluemix.net/docs/services/IoT/devices/api.html
https://console.ng.bluemix.net/docs/services/IoT/applications/api.html
