### ISSUE TITLE
Error in object storage security documentation

### ISSUE THREAD

**Issue by paulata** [IBM-Bluemix/docs#894]
The web page https://console.ng.bluemix.net/docs/services/ObjectStorage/os_security.html#read-access generated from the md file in this repo https://github.com/IBM-Bluemix/docs/blob/master/services/ObjectStorage/os_security.md has errors and displays the md file incorrectly.
For example the web page has a missing asterisk - it shows "Read and list for all referers and listing	.r:,.rlistings" but it should be as in the md file .r:*,.rlistings

**Comment by smguilia** [comment]
Thank you for letting me know @paulata. I am aware of this issue and am planning to push the fix today. I will let you know when the fix is live. Please let me know if you see any other places the documentation could be improved.

**Comment by smguilia** [comment]
@paulata The docs are live with the correction. You can find them here: https://console.ng.bluemix.net/docs/services/ObjectStorage/os_security.html

Thank you for letting me know.
