### ISSUE TITLE
OpenWhisk missing from main Compute Menu in Docs

### ISSUE THREAD

**Issue by csantanapr** [IBM-Bluemix/docs#907]
OpenWhisk was listed here, and the last few days now it's gone.

https://console.ng.bluemix.net/docs/

![image](https://cloud.githubusercontent.com/assets/1094878/20965866/aca9a13c-bc45-11e6-8ee5-7dd1f90cea53.png)

**Comment by jenschlot** [comment]
@csantanapr Should be fixed. Take a look?

**Comment by csantanapr** [comment]
yes fixed
