### ISSUE TITLE
Cordova Getting Started Step 7 Incorrectly Telling User to Use Build/Run iOS Instead of Xcode

### ISSUE THREAD

**Issue by YoungJM** [IBM-Bluemix/docs#97]
In step 5 of the  Cordova Getting Started document when informing the user how to setup the iOS platform the document states to run the application through Xcode (which is correct, otherwise you overwrite your bridging-header). 

However, in step 7 the document confuses the user by telling them to run the mobile application using `cordova build ios` and `cordova run ios` which is incorrect and results in compile errors. 

Please update the document to clarify to the user to only build and run iOS code through Xcode for the HelloWorld sample.

Thanks

**Comment by tionaf** [comment]
Thanks, James. I will update the steps accordingly.

**Comment by tionaf** [comment]
Hi James - I worked with the Cordova developer to update the instructions. The most recent version has been tested and should not cause any compile errors. I'm requesting a production update today. Thanks!

**Comment by jeffchi** [comment]
@YoungJM  I assume all the steps are updated in the doc, and therefore closing this issue.
Let us know if anything else you need.
:+1:

**Comment by YoungJM** [comment]
I am still seeing that Step 7 tells the user to build and run iOS from the using cordova CLI which still results in build errors on my end.

The issue here is just the format of the steps. You're telling the user to build and run through Xcode at the end of step 5 before they've even added the App ID and route in step 6 and then telling them to build and run again using the cordova CLI in step 7 which I do not believe works.

In my opinion Step 6 needs to be switched with Step 5 and the first part of Step 7 telling the user to build/run through cordova CLI should be removed.

**Comment by tionaf** [comment]
Hi James, I sent you a note with a link to the updated topic on stage 1.

**Comment by YoungJM** [comment]
Hi Tiona, the updated doc is better but we're still telling the user to execute 'build ios' and 'ruin ios' which only results in compile errors on my end again due to I imagine the bridging header being overwritten on 'build ios'. I would still suggest simply removing all instances of building or running ios through the command line.

**Comment by tionaf** [comment]
Got it. I removed 'build ios' and 'run ios'. The latest version is showing on stage 1. If the changes look OK to you, I'll request a production update for this topic.

**Comment by YoungJM** [comment]
Yes I think that will work. Thanks Tiona
