### ISSUE TITLE
The documentation still label the VPN service in BETA

### ISSUE THREAD

**Issue by sarielda** [IBM-Bluemix/docs#971]
Not sure if anything needs to be updated in the documentation details but I'd appreciate if you could reflect the GA status of the service on the documentation page.

**Comment by sarielda** [comment]
@sefuhrer it still shows Beta: https://www.ng.bluemix.net/docs/services/vpn/index.html

**Comment by jenschlot** [comment]
@sarielda That link should be redirecting now to the latest VPN docs...take a look?

**Comment by sarielda** [comment]
@jenschlot yes it's good now. Thank you!
