### ISSUE TITLE
nav and page content out of order

### ISSUE THREAD

**Issue by trevorbodz** [IBM-Bluemix/docs#98]
looking at the object store docs and on the page I see "Using the Object Storage user interface” and then I see "Using the Swift CLI to access Object Storage” but in the left nav they are reversed, so when scrolling there is a weird “jump” in the nav that it skips the entry for "Using the Swift CLI to access Object Storage” and then goes back to the UI menu item

https://console.ng.bluemix.net/docs/services/ObjectStorage/index.html#creating-object-storage-instance

**Comment by jiamaoIBM** [comment]
Then navigation is updated to match the content order. Thanks!

https://console.stage1.eu-gb.bluemix.net/docs/services/ObjectStorage/index.html
