### ISSUE TITLE
Link to 'Configure CLI' is broken

### ISSUE THREAD

**Issue by danifitz** [IBM-Bluemix/docs#99]
In [this section](https://github.com/IBM-Bluemix/docs/blob/master/openwhisk/index.md#setting-up-sitedatakeywordopenwhisk_short) the link to 'Configure CLI' is broken - the link is https://www.ng.bluemix.net/openwhisk/cli but clicking on it I get the following message: 

404 Not Found: Requested route ('www.ng.bluemix.net') does not exist.

**Comment by danifitz** [comment]
related to this issue, the instructions on this [page](https://new-console.ng.bluemix.net/openwhisk/cli) don't work for me. Is this the right place to raise this issue or if not please point me in the right direction..

**Comment by sefuhrer** [comment]
This is the correct location to open this issue. I have fixed your original issue - the url was missing "console". For your second issue, which instructions specifically are failing to work for you?

**Comment by danifitz** [comment]
I have just checked and when I click the [Configure CLI](https://ng.bluemix.net/openwhisk/cli) link on [this page](https://new-console.ng.bluemix.net/docs/openwhisk/index.html) I am redirected to https://console.ng.bluemix.net/

Instruction number 1, when I run the command 

`sudo pip install --upgrade https://new-console.ng.bluemix.net/openwhisk/cli/download`

I get an error (see installerror.log).
[installerror.txt](https://github.com/IBM-Bluemix/docs/files/157062/installerror.txt)

Python version == `Python 2.7.8`

Pip version == `pip 1.5.6 from /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg (python 2.7)`

**Comment by csantanapr** [comment]
This is fix now
